name: "(front) Linter"

on:
  workflow_dispatch:
  push:
    paths:
      - 'front/**'
    branches:
      - main
  pull_request:
      paths:
      - 'front/**'

defaults:
  run:
    working-directory: front

jobs:
  eslint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'front'
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
